version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: gfg-postgres
    environment:
      POSTGRES_DB: gfg_udemy
      POSTGRES_USER: strapi_admin
      POSTGRES_PASSWORD: StrongPassword123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
